services:
  backend:
    build: ./backend
    environment:
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    expose:
      - "8080"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
